# Generated by Django 2.0.4 on 2018-04-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter music component (e.g. Guitar, Piano, Drums, Bass, etc.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter music genre (e.g. Rock, Psychedelic, Trance, etc.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('components', models.ManyToManyField(to='soundboard.Component')),
                ('contributors', models.ManyToManyField(to='soundboard.Contributor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='soundboard.Contributor')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='soundboard.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='preferences',
            field=models.ManyToManyField(to='soundboard.Genre'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='skills',
            field=models.ManyToManyField(to='soundboard.Component'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
